UMC-CARDIFY/Server

src/main/java/com/umc/cardify/config/exception/BadRequestException.java, src/main/java/com/umc/cardify/config/exception/DatabaseException.java, src/main/java/com/umc/cardify/config/exception/ErrorResponse.java, src/main/java/com/umc/cardify/config/exception/ErrorResponseStatus.java, src/main/java/com/umc/cardify/config/exception/ExceptionAdvice.java
- close #2
- 어플리케이션 내 Exception 처리 공통 로직 구현
- 선택 사항
=> [#2] Exception 처리 공통 로직 구현

build.gradle, src/main/java/com/umc/cardify/config/MultipartJackson2HttpMessageConverter.java, src/main/java/com/umc/cardify/config/SwaggerConfig.java, src/main/java/com/umc/cardify/controller/UserController.java, src/main/java/com/umc/cardify/dto/user/UserRequest.java, src/main/java/com/umc/cardify/dto/user/UserResponse.java
- close #4 
- 스웨거 초기 세팅 및 유저 컨트롤러 & dto에 어노테이션 적용
- 선택 사항
=> [#4] [Feat] 스웨거 초기 세팅

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/converter/FolderConverter.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Folder.java, src/main/java/com/umc/cardify/dto/folder/FolderRequest.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #5 
- 아카이브 내의 노트 화면 조회
데이터베이스에 저장된 folder_id=1을 입력했을 때 모든 노트가 조회 되는 것을 확인
=> [#5] 모든 노트 조회 기능 구현

src/main/java/com/umc/cardify/config/WebConfig.java, src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/controller/UserController.java
- close #14
- api URL 수정 및 WebConfig에 URL 추가 (토큰 검증)
앞으로 만드는 controller들에는 api/v1을 필수로 추가
- 선택 사항
=> [#14] API URL 전체 수정

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Folder.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #16 
-  조회 기능 페이징 수정 ( currentPage =1 )
- 토큰을 사용한 노트 목록 조회
앞으로 currentPage는 1로 통일
- 선택 사항
=> [#16] 모든 노트 조회 기능 수정

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/converter/FolderConverter.java, src/main/java/com/umc/cardify/domain/Folder.java, src/main/java/com/umc/cardify/domain/User.java, src/main/java/com/umc/cardify/dto/folder/FolderRequest.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #11 
- 토큰을 사용한 폴더 목록 조회
- User, Folder 관계성 추가
- 선택 사항
=> [#11] 모든 폴더 조회 기능 추가

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #18 //
- noteId 입력시 해당 노트 삭제
- 없는 noteId입력시 오류 처리
- 연관 카드 cascade 삭제
=> [#18] 노트 삭제

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/FolderService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #23  //
- 폴더 아이디와 검색어가 주어진다면, 북마크된 노트와 되지 않은 노트로 구분해서 반환
- 검색어를 비운 채로 보내면 전체가 반환 
제목에 관해서만 검색 로직 작성 -> 추후 내용에 대한 검색도 추가해야 한다면 수정해야 함.
- 선택 사항
=> [#23] 특정 폴더 내 노트 검색

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #21  
- order 파라미터로 폴더 정렬 방식 지정
- ResponseDTO의 InfoDTO인 전체 데이터는 기본으로 두고, 정렬/필터링 등의 기능부터는 따로 DTO를 만들어서 사용 예정
- 선택 사항
=> [#21] 폴더 정렬 기능

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #27  //
- 노트 아이디, 즐겨찾기 여부를 입력받아 데이터베이스에 저장
=> [#27] 노트 즐겨찾기

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #26  //
- 사용자가 만든 특정한 폴더와 하위 노트, 카드가 함께 삭제되는 기능
=> [#26] 폴더 삭제 기능

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/dto/folder/FolderRequest.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #31  //
- 유저 토큰을 받아서 폴더 생성 구현 | 폴더의 이름과 색상이 생성 시 결과 값으로 반환 됨
- 유저마다 폴더 생성 가능 | 해당 폴더 안에 노트 생성 가능하고 삭제까지 테스트 함
- 유저마다 가지고 있는 폴더 이름을 확인해서 중복되면 예외 처리
사용자 확인 후 폴더의 이름과 색상 입력하고 생성(DB에 폴더 이름, 색상 저장됨)
결과 값은 201로 생성됨을 나타내게 함(중복된 이름은 허용 안 함)
=> [#31] 폴더 추가 기능

src/main/java/com/umc/cardify/config/exception/ErrorResponseStatus.java, src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #29  //
- 각 노트 api를 작동할 때 토큰 내 userId와 조작하려는 노트의 userId가 일치하는지 검증
=> [#29] 노트 API 유저아이디 검증

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #36 //
- 노트 검색 기능 변경에 따른 이름 변경(노트 검색->특정 폴더 내 노트 조회) 및 로직 변경(검색어 삭제 및 모든 노트 조회)
=> [#36] 특정 폴더 내 노트 조회

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/domain/Folder.java, src/main/java/com/umc/cardify/dto/folder/FolderRequest.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #34  //
- 사용자 토큰에 따른 폴더 수정 기능(다른 유저의 폴더는 수정 안되는 것 확인 -> 결과는 500) | 색상은 상관없음
- 사용자에게 수정하려는 폴더 이름이 이미 있다면 중복 값으로 에러 처리 됨
수정하려는 폴더 이름이 이미 있는 경우
=> [#34] 폴더 수정 기능

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/domain/Folder.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #41  //
- 특정 폴더를 즐겨 찾기(ACTIVE) 등록
- 특정 폴더의 markState 상태에 따라서 ACTIVE/INACTIVE로 값이 반환
=> [#41] 특정 폴더 즐겨찾기 기능

build.gradle, src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #36  //
- 특정 폴더 내 노트 조회시 페이징 및 노트 정렬 추가
- request에 페이징 관련 변수가 없다면, 모든 노트 조회
=> [#36]: 노트 조회시 페이징, 노트 정렬 기능 추가

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #23 //
- 노트 검색 기능이 변경됨에 따라 노트 검색 세부 기능 수정
- 검색 시 같은 폴더에 있는 노트들의 내용에서 검색이 됨
문단 단위로 결과를 반환하는데 프론트에서 문단을 어떤 방식(ex.\n)으로 구분하는 미정임.
추후에 결정되면 수정 요망(현재는 마침표로 구분 중)
- 선택 사항
=> [#23]: 노트 검색 기능 수정

src/main/java/com/umc/cardify/domain/Folder.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #48   //
-  폴더 엔티티에 즐겨찾기 수정 날짜 저장 필드 생성 - markDate
- markDate가 즐겨찾기를 할 경우, 스웨거에서 현재 시간이 저장되는지 확인
=> [#48] 폴더 즐겨찾기 수정일 필드 추가

src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #27  //
- 노트를 즐겨찾기한 시간 순서대로 정렬(늦게 즐겨찾기 누른 노트가 상단에 위치)
- 선택 사항
=> [#27]: 노트 즐겨찾기 추가 및 조회 기능 변경

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/service/FolderService.java, src/main/java/com/umc/cardify/service/security/CustomUserDetailsService.java
- close #57  //
- cors 에러 및 403에러 해결 
- 500 서버 에러 해결 
- 선택 사항
=> [FEAT]#57 : 스웨거 CORS 에러 및 403 에러 해결

src/main/java/com/umc/cardify/domain/Folder.java
- close #61  //
- folder 컬럼 오타 수정 (mark_sate-> mark_state)
- 선택 사항
=> [FIX]#61 : ec2 500 에러 해결

src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/dto/library/LibraryRequest.java, src/main/java/com/umc/cardify/dto/library/LibraryResponse.java, src/main/java/com/umc/cardify/repository/LibraryCategoryRepository.java, src/main/java/com/umc/cardify/service/LibraryService.java
- close #67 //
- 카테고리 이름, 아이디, 카테고리 별 노트 개수 반환
- 선택 사항
=> [#67] 자료실 전체 카테고리 조회

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #74  //
- 공유 기능 수정에 따른 코드 변경
- 카드 포함 삭제(다운로드시 카드 포함 여부 선택), 편집 허용 삭제, 링크 공유 삭제
- 선택 사항
=> [#74] 공유 기능 수정

src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Download.java, src/main/java/com/umc/cardify/domain/Library.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/domain/User.java, src/main/java/com/umc/cardify/dto/library/LibraryRequest.java, src/main/java/com/umc/cardify/dto/library/LibraryResponse.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/DownloadRepository.java, src/main/java/com/umc/cardify/service/CardService.java, src/main/java/com/umc/cardify/service/LibraryService.java
- close #76  //
- 자료실에 업로드된 노트 다운로드
- 노트 조회시 다운로드한 노트 구분
- 노트 다운로드시 포인트 차감
- 선택 사항
=> [#76] 자료실 다운로드

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Download.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/service/LibraryService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #78  //
- 노트가 업로드된 상태라면 수정을 못하도록 막음
- 노트 조회시 업로드한 노트 구분
- 선택 사항
=> [#78] 노트 작성 및 노트 업로드 수정

src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/dto/library/LibraryResponse.java, src/main/java/com/umc/cardify/repository/DownloadRepository.java, src/main/java/com/umc/cardify/service/LibraryService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #80   //
- 일주일간 다운로드가 많은 노트 3개를 조회
유저 이미지가 추가되면 반환값에 유저 이미지 삽입
- 선택 사항
=> [#80] 자료실 추천 노트 조회

src/main/java/com/umc/cardify/config/CorsConfig.java, src/main/java/com/umc/cardify/config/SecurityConfig.java, src/main/java/com/umc/cardify/config/WebConfig.java
=> [FIX] #45 : CORS 에러 해결을 위한 Config 파일 수정

src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/dto/library/LibraryResponse.java, src/main/java/com/umc/cardify/service/LibraryService.java
- close #86 //
- 업로드 수를 반영해 상위 3개의 카테고리를 반환
- 선택 사항
=> [#86] 인기 카테고리 조회

src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/service/LibraryService.java
- close #90  //
- 카테고리 이름 입력시 해당 카테고리를 갖고 있는 자료실 데이터 반환
- 선택 사항
=> [#90] 특정 카테고리 내 노트 조회 

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/dto/card/CardRequest.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/repository/OverlayRepository.java, src/main/java/com/umc/cardify/service/CardService.java, src/main/resources/application.yml
- close #93
- 이미지 카드 id를 통해 해당 이미지카드와 가림판 정보를 조회하는 기능을 구현
- 선택 사항
=> [#93] 이미지 카드 조회 

src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/converter/LibraryConverter.java, src/main/java/com/umc/cardify/dto/library/LibraryRequest.java, src/main/java/com/umc/cardify/dto/library/LibraryResponse.java, src/main/java/com/umc/cardify/service/LibraryService.java
- close #92  //
- 검색어와 카테고리를 필터링 한 뒤 해당 조건에 맞는 노트들 인기순으로 반환
- 선택 사항
=> [#92] 자료실 노트 검색

src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/converter/LibraryConverter.java, src/main/java/com/umc/cardify/dto/library/LibraryResponse.java, src/main/java/com/umc/cardify/service/LibraryService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #99 //
- 특정 카테고리 내 노트 조회 정렬 추가
- 노트 목록 조회 API Response 수정
- 선택 사항
=> [#99] 특정 카테고리 내 노트 조회 정렬 추가

src/main/java/com/umc/cardify/dto/folder/FolderComparator.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #109 
- 폴더 조회 기능 안의 edit_date 를 비교하는 코드 수정
- 정렬 기능의 문자/숫자 비교 코드 수정
- 폴더 수정 시, 기존 파일 이름 사용 제한 수정
- 선택 사항
=> [#109] 폴더 조회/정렬 기능 추가 수정

src/main/java/com/umc/cardify/config/SecurityConfig.java, src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/NoteRepository.java
- close #111 //
- 노트 조회 Service / Response에 folderId 추가
- SecurityConfig 수정 및  RequestHeader 주석 처리 제거
- 선택 사항
=> [#111] 노트 조회 색상 반환 및 SecurityConfig, RequestHeader 주석 처리 제거

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/service/FolderService.java
- close #113  //
- 색상 값을 List<String>으로 받아서 ','로 구분하는 코드 추가
- 선택 사항
=> [#113] 폴더 필터링 기능 추가

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/domain/ImageCard.java, src/main/java/com/umc/cardify/repository/OverlayRepository.java, src/main/java/com/umc/cardify/service/CardService.java, src/main/resources/application.yml
- close #108 
- 이미지 카드 편집 기능 추가
- 선택 사항
=> [#108] 이미지 카드 편집 기능 추가

src/main/java/com/umc/cardify/controller/FolderController.java
- close #116  //
- 폴더 삭제 기능 코드 수정
- 선택 사항
=> [#116] 폴더 삭제 수정

src/main/java/com/umc/cardify/service/FolderService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #118  //
- 아카이브 내 전체 조회 기능 페이지 사이즈 수정
- 선택 사항
=> [#118] 페이지 사이즈 수정

src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/domain/ProseMirror/Attr.java, src/main/java/com/umc/cardify/domain/ProseMirror/Mark.java, src/main/java/com/umc/cardify/domain/ProseMirror/Node.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #103   //
- 입력값이 ProseMirror의 객체로 변경됨에 따라 작성, 조회, 검색 및 데이터베이스 구조 변경
- 선택 사항
=> [#103] 노트 작성 및 조회 API 수정

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/domain/Folder.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/FolderService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #121  //
- 노트 필터링 기능 추가
- 색상 리스트를 ','로 구분해서 값 추출
- 폴더 이름/색상 길이 제한 제거
- 선택 사항
=> [#121] 노트 필터링 기능

src/main/java/com/umc/cardify/config/exception/ErrorResponseStatus.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/domain/enums/CardType.java, src/main/java/com/umc/cardify/service/CardService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #3 //
- 빈칸 카드 추출 및 저장 로직 구현
- 선택 사항
=> [#120] 빈칸 카드 생성(추출)

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/FolderService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #124  //
- 전체 노트 정렬 기능 추가(이름/생성일 기준)
- 선택 사항
=> [#124] 전체 노트 목록 정렬 기능

src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/LibraryConverter.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/dto/library/LibraryResponse.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/DownloadRepository.java, src/main/java/com/umc/cardify/service/LibraryService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #125  //
- 자료실 아이디를 받으면 해당 자료를 다운받은 방식 반환
- 노트 조회 api 수정
- 선택 사항
=> [#125] 자료실 다운로드 여부 조회

src/main/java/com/umc/cardify/dto/folder/FolderComparator.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/service/FolderService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #131  
- 쿼리와 java 정렬의 충돌로 인해 Comparator 파일로 정렬 통일
- 선택 사항
=> [#131] 폴더 페이지 사이즈에 따른 정렬 오류 수정

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/domain/StudyCardSet.java, src/main/java/com/umc/cardify/domain/enums/StudyStatus.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/repository/StudyCardSetRepository.java, src/main/java/com/umc/cardify/service/CardService.java, src/main/java/com/umc/cardify/service/NoteService.java
- close #101 
- 플래시 카드 목록 조회 기능 구현
- StudyCardSet ( 노트 내 카드 묶음) 엔티티 구현
- 선택 사항
=> [#101] 플래시 카드 목록 조회

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/domain/ImageCard.java, src/main/java/com/umc/cardify/dto/card/CardRequest.java, src/main/java/com/umc/cardify/repository/StudyCardSetRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java, src/main/java/com/umc/cardify/service/LibraryService.java, src/main/java/com/umc/cardify/service/NoteComponentService.java, src/main/java/com/umc/cardify/service/NoteModuleService.java
- close #137 
- 이미지 카드에 StudyCardSet 필드 추가
- NoteService, CardService 계층 Model과 Component로 분리 
- 선택 사항
=> [#137] 이미지 카드에 StudyCardSet 필드 추가, NoteService, CardService 계층 Model과 Component로 분리 

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/repository/CardRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
- close #136 
- 기존 플래시카드 메인 화면 API 관련 메소드 및 DTO 이름 수정, 일반학습 API 구현
- 선택 사항
=> [#136] 학습 카드 - 일반 학습 API 구현

src/main/java/com/umc/cardify/config/exception/ErrorResponseStatus.java, src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/domain/enums/Difficulty.java, src/main/java/com/umc/cardify/dto/card/CardRequest.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
- close #141 
- 난이도 선택 및 업데이트 API 구현
- 선택 사항
=> [#141 ] 난이도 선택(분석 학습) API 구현

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/domain/enums/Difficulty.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
=> [#143] 학습 카드 그래프 조회 API 구현

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/domain/ImageCard.java, src/main/java/com/umc/cardify/domain/StudyLog.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/repository/CardRepository.java, src/main/java/com/umc/cardify/repository/StudyLogRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
- close #148 
- 분석 학습 완료 API, 분석 학습 기록 조회 API 구현
- 선택 사항
=> [#148] 분석 학습 기록 조회

src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/service/CardComponentService.java
=> [FIX] #151 : 카드 학습 DTO에 cardId 추가

src/main/java/com/umc/cardify/config/exception/ErrorResponseStatus.java, src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/domain/ProseMirror/Attr.java, src/main/java/com/umc/cardify/service/CardModuleService.java, src/main/java/com/umc/cardify/service/NoteComponentService.java
- close #150 
- Attrs 클래스 수정
- NoteController 노트 작성 메소드에 이미지 파일 인자로 추가
- NoteService 및 CardService 수정 및 개선
- 선택 사항
=> [ #150 ] 노트 작성 API에 이미지 카드 추출 및 생성 로직 추가

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/converter/LibraryConverter.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/domain/ImageCard.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/repository/CardRepository.java, src/main/java/com/umc/cardify/repository/ImageCardRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
=> [#147] 카드 학습 시 이미지 카드 포함

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/service/CardComponentService.java
=> [#155]  카드 학습 응답 DTO에 카드 id 및 이미지 카드 id 포함

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/dto/card/CardRequest.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
=> [#158] 난이도 선택에 이미지 카드 추가, 카드 학습시 noteId, folderId 전달

src/main/java/com/umc/cardify/domain/ImageCard.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
=> [#162]  모든 분석학습 API에 이미지 카드 추가 완료

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/service/CardComponentService.java
=> [#165]  플래시 카드에 즐겨찾기 정보 추가

build.gradle, src/main/java/com/umc/cardify/config/SecurityConfig.java, src/main/java/com/umc/cardify/controller/UserController.java, src/main/java/com/umc/cardify/domain/User.java, src/main/java/com/umc/cardify/dto/user/UserRequest.java, src/main/java/com/umc/cardify/dto/user/UserResponse.java, src/main/java/com/umc/cardify/jwt/JwtUtil.java, src/main/java/com/umc/cardify/repository/UserRepository.java, src/main/java/com/umc/cardify/service/UserService.java, src/main/resources/application.yml
- close #160  //
- 마이페이지 기능 구현 완료 
- 로그아웃 기능 구현 완료(리프래스 토큰 무효화)
- 선택 사항
=> [#160] 마이페이지 기능 구현 완료 

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/FolderService.java, src/main/java/com/umc/cardify/service/NoteComponentService.java
- close #159 
- 폴더 정렬과 필터링 기능 통합
- 노트 정렬과 필터링 기능 통합
- 잘못된 order 혹은 color 입력받으면 에러나
- 선택 사항
=> [#159] 정렬과 필터링 동시 사용을 위한 기능 통합

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/domain/Card.java, src/main/java/com/umc/cardify/dto/card/CardRequest.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/repository/CardRepository.java, src/main/java/com/umc/cardify/repository/StudyCardSetRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java, src/main/java/com/umc/cardify/service/NoteComponentService.java
=> [#164] 분석 학습 제안

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/domain/StudyCardSet.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
=> [#170] 학습 카드셋 삭제, 카드 학습 시 cardType DTO에 추가

src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/service/FolderService.java, src/main/java/com/umc/cardify/service/NoteComponentService.java
- close #173   //
- 폴더 조회 기능 통합(FolderService 수정)
- 선택 사항
=> [#173] 폴더 조회 기능 통합

src/main/java/com/umc/cardify/domain/ContentsNote.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/repository/ContentsNoteRepository.java, src/main/java/com/umc/cardify/service/LibraryService.java, src/main/java/com/umc/cardify/service/NoteComponentService.java
- close #179  //
- 탐색 속도 향상을 위한 노트 엔티티에서 노트 내용 분리
- 선택 사항
=> [#179] 노트 내용 분리

src/main/java/com/umc/cardify/CardifyApplication.java, src/main/java/com/umc/cardify/controller/UserController.java, src/main/java/com/umc/cardify/domain/User.java, src/main/java/com/umc/cardify/dto/user/UserResponse.java, src/main/java/com/umc/cardify/repository/UserRepository.java, src/main/java/com/umc/cardify/service/UserService.java
=> [#171] 출석 체크 API 구현

src/main/java/com/umc/cardify/service/CardComponentService.java
=> [#184] 분석 학습 완료 시 Card 들 중 가장 빠른 다음 학습일을 StudyCardSet에 저장

src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/library/LibraryRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/service/LibraryService.java, src/main/java/com/umc/cardify/service/NoteComponentService.java
- close #183  //
- 노트 다운로드 방식 수정(카드 포함 여부 -> 편집 허용 여부)
- 선택 사항
=> [#183] 노트 다운로드 방식 수정

src/main/java/com/umc/cardify/domain/ImageCard.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/repository/ImageCardRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
=> [#186 ] 영구 보관 및 학습 상태 관련 기능 구현, 분석 학습 제안 시 이미지 카드 및 카드 id 추가

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/repository/CardRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java
- close #145  //
- 학습한 카드의 요일 별 개수와 한 주에 대한 총 학습 개수 반환
- 선택 사항
=> [#145] 대시보드 주간 학습 결과 조회 기능

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/repository/StudyLogRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java
=> [#190] 분석학습 - 재학습, Note 엔티티 수정

src/main/java/com/umc/cardify/domain/enums/StudyStatus.java, src/main/java/com/umc/cardify/dto/card/CardResponse.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
=> [#193] 카드 학습시 멀티 카드 배열 전달, 카드 타입 세분화

src/main/java/com/umc/cardify/config/exception/ErrorResponseStatus.java, src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/domain/enums/StudyStatus.java, src/main/java/com/umc/cardify/repository/StudyCardSetRepository.java, src/main/java/com/umc/cardify/service/CardComponentService.java, src/main/java/com/umc/cardify/service/CardModuleService.java
- close #194 
- 반환 값 Page에서 List로 수정 (무한스크롤)
- 선택 사항
=> [#194] 플래시 카드 정렬 & 필터링 

src/main/java/com/umc/cardify/controller/CardController.java, src/main/java/com/umc/cardify/dto/card/CardRequest.java, src/main/java/com/umc/cardify/service/CardComponentService.java
=> [FIX] #197 : 분석 학습 제안 GET -> POST 방식으로 수정

build.gradle, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/domain/ContentsNote.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/ContentsNoteRepository.java, src/main/java/com/umc/cardify/service/LibraryService.java, src/main/java/com/umc/cardify/service/NoteComponentService.java, src/main/resources/application.yml
- close #199  //
- 노트 내용을 MongoDB로 분리하여 관리
- 그에 따라 노트 추가, 작성, 자료실 다운로드 수정
- 선택 사항
=> [#199] DB 다중화

src/main/java/com/umc/cardify/config/exception/ErrorResponseStatus.java, src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/domain/Folder.java, src/main/java/com/umc/cardify/dto/folder/FolderResponse.java, src/main/java/com/umc/cardify/repository/FolderRepository.java, src/main/java/com/umc/cardify/service/FolderService.java
=> [#201] 하위 폴더 생성

src/main/java/com/umc/cardify/auth/oauth/OAuth2Attributes.java, src/main/java/com/umc/cardify/auth/oauth/OAuth2SuccessHandler.java, src/main/java/com/umc/cardify/config/SecurityConfig.java, src/main/resources/application.yml
- close #210  //
- 구글 로그인 설정 
- 선택 사항
=> [#210] 구글 로그인 설정 완료

src/main/java/com/umc/cardify/auth/oauth/OAuth2SuccessHandler.java, src/main/resources/application.yml
- close #212  //
- 토큰 url 노출 안 되도록 쿠키에 저장 
- 카카오 동의하기 화면 출력
- 선택 사항
=> [#212] 토큰 쿠키에 저장

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/service/NoteComponentService.java, src/main/resources/application.yml
- close #208  
- 폴더 내 노트에서 검색에서 전체 범위 내 검색이 가능하도록 변경
- 선택 사항
=> [#208] 노트 검색 기능 수정

src/main/java/com/umc/cardify/service/FolderService.java
- close #215 
- 구독 기능에 따른 폴더 생성 제한
- 선택 사항
=> [#215] 구독 여부에 따른 폴더 생성 제한

src/main/java/com/umc/cardify/converter/NoteConverter.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/NoteRepository.java
- close #220 
- 특정 노트의 카드 개수 조회
- 선택 사항
=> [#220] 특정 폴더 조회: 노트의 카드 개수(flashCardCount) 조회

src/main/java/com/umc/cardify/domain/CustomOAuth2User.java, src/main/java/com/umc/cardify/domain/PaymentMethod.java, src/main/java/com/umc/cardify/domain/Product.java, src/main/java/com/umc/cardify/domain/Subscription.java, src/main/java/com/umc/cardify/domain/SubscriptionPayment.java, src/main/java/com/umc/cardify/domain/User.java, src/main/java/com/umc/cardify/domain/enums/PaymentStatus.java, src/main/java/com/umc/cardify/domain/enums/PaymentType.java, src/main/java/com/umc/cardify/domain/enums/SubscriptionStatus.java, src/main/resources/application.yml
- close #223  //
- 결제 관련 DB 구축
- 선택 사항
=> [FEAT] 결제 관련 엔터티 생성 및 관계 매핑

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/domain/SearchHistory.java, src/main/java/com/umc/cardify/domain/User.java, src/main/java/com/umc/cardify/repository/SearchHistoryRepository.java, src/main/java/com/umc/cardify/service/NoteComponentService.java, src/main/resources/application.yml
- close #218 //
- 검색시 검색 기록에 검색어 삽입
- 검색 기록 삭제시 해당 레코드 삭제
- 선택 사항
=> [#218] 검색 기록 추가 및 삭제 기능 구현

src/main/java/com/umc/cardify/auth/oauth/OAuth2SuccessHandler.java, src/main/java/com/umc/cardify/config/CorsConfig.java, src/main/java/com/umc/cardify/config/SecurityConfig.java, src/main/java/com/umc/cardify/controller/AuthController.java
- close #234  //
- access token은 로컬 스토리지에 저장, refresh token은 쿠키에 저장 
- 선택 사항
=> [#234] 토큰 저장 방식 로컬 스토리지로 수정 

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/domain/Note.java, src/main/java/com/umc/cardify/dto/note/NoteRequest.java, src/main/java/com/umc/cardify/dto/note/NoteResponse.java, src/main/java/com/umc/cardify/repository/NoteRepository.java, src/main/java/com/umc/cardify/service/NoteComponentService.java
- close #238 //
- 노트 링크 생성시 uuid를 db에 저장
- 해당 uuid를 통해 노트를 조회
- 노트 아이디를 입력받아 링크 공유 취소
- 선택 사항
=> [#238] 노트 링크 공유 기능 구현

build.gradle, src/main/java/com/umc/cardify/auth/jwt/JwtAuthenticationFilter.java, src/main/java/com/umc/cardify/auth/jwt/JwtTokenProvider.java, src/main/java/com/umc/cardify/auth/oauth/CustomUserDetailsService.java, src/main/java/com/umc/cardify/config/CorsConfig.java, src/main/java/com/umc/cardify/config/EncryptionUtil.java, src/main/java/com/umc/cardify/config/exception/ErrorResponseStatus.java, src/main/java/com/umc/cardify/config/exception/ResourceNotFoundException.java, src/main/java/com/umc/cardify/controller/AuthController.java, src/main/java/com/umc/cardify/controller/FolderController.java, src/main/java/com/umc/cardify/controller/LibraryController.java, src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/controller/PaymentMethodController.java, src/main/java/com/umc/cardify/controller/UserController.java, src/main/java/com/umc/cardify/domain/PaymentMethod.java, src/main/java/com/umc/cardify/domain/Product.java, src/main/java/com/umc/cardify/domain/Subscription.java, src/main/java/com/umc/cardify/domain/SubscriptionPayment.java, src/main/java/com/umc/cardify/domain/User.java, src/main/java/com/umc/cardify/dto/payment/card/PaymentMethodRequest.java, src/main/java/com/umc/cardify/dto/payment/card/PaymentMethodResponse.java, src/main/java/com/umc/cardify/dto/subscription/card/PaymentMethodRequest.java, src/main/java/com/umc/cardify/dto/subscription/card/PaymentMethodResponse.java, src/main/java/com/umc/cardify/repository/PaymentMethodRepository.java, src/main/java/com/umc/cardify/repository/UserRepository.java, src/main/java/com/umc/cardify/service/PaymentMethodService.java, src/main/java/com/umc/cardify/service/UserService.java, src/main/resources/application.yml, src/main/resources/static/token-check.html
- close #225  //
- 결제 수단 조회, 등록, 삭제, 기본 결제 수단 변경
- 이메일 중복 시 에러 해결
- 토큰 관련 코드 수정 (@afflogy @ohige01 확인 부탁합니다)
- 선택 사항
=> [#225] 결제 수단 관련 API 완료 및 로그인 중복 에러 해결 

build.gradle, src/main/java/com/umc/cardify/repository/SubscriptionRepository.java, src/main/java/com/umc/cardify/service/alert/AlertService.java, src/main/java/com/umc/cardify/service/alert/DiscordAlertService.java, src/main/java/com/umc/cardify/service/alert/EmailAlertService.java, src/main/java/com/umc/cardify/service/alert/NotificationService.java, src/main/java/com/umc/cardify/service/payment/PortoneClient.java, src/main/java/com/umc/cardify/service/payment/SimplePayServiceImpl.java, src/main/java/com/umc/cardify/service/subscription/SubscriptionServiceImpl.java, src/main/resources/application.yml
- close #245  //
- 걸제 실패시 이메일로 알림 서비스
=> [#245] 결제 실패시 이메일 알림 서비스

src/main/java/com/umc/cardify/controller/NoteController.java, src/main/java/com/umc/cardify/service/NoteComponentService.java, src/main/resources/application.yml
- close #261  //
- 노트 내 카드리스트 조회
- 구현 화면입니다.
=> [#261] 노트 내 카드 조회 구현
